pipeline {
    agent any

    stages {
        stage("Clone repo") {
            steps {
                checkout scm
            }
        }

        stage("Build Docker Image") {
            steps {
                dir('devops-aws-project/docker') {
                    sh "docker build -t sricharanchebolu/devops-app ."
                }
            }
        }

        stage("Docker Login") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-cred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                }
            }
        }

        stage("Push to Docker Hub") {
            steps {
                sh "docker push sricharanchebolu/devops-app"
            }
        }

        stage("Terraform init") {
            steps {
                dir('devops-aws-project/terraform') {
                    withCredentials([usernamePassword(
                        credentialsId: 'aws-cred',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )]) {
                        sh "terraform init"
                    }
                }
            }
        }

        stage("Terraform apply") {
            steps {
                dir('devops-aws-project/terraform') {
                    withCredentials([usernamePassword(
                        credentialsId: 'aws-cred',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )]) {
                        sh 'terraform apply -auto-approve -var="key_name=devops-aws-pipeline"'
                    }
                }
            }
        }
    }
}
